version: '3.8'

services:
  web:
    build: ./mysite
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./mysite/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod