version: '3.8'

services:
  web:
    build: ./mysite
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/home/app/web/static
    env_file:
      ./.env.prod
    command: /prepare_nginx_conf.sh
    depends_on:
      - web

volumes:
  static_volume: