version: '3.8'

services:
  web:
    build: ./mysite
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod

volumes:
  static_volume:
